// Protocol Buffers schema for Anchor node registry and content exchange payloads.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: anchor.proto

package membusspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentExchangePayload represents the list of sealed MIDs
// exchanged over the direct content-exchange stream protocol.
type ContentExchangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mids          []string               `protobuf:"bytes,1,rep,name=mids,proto3" json:"mids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentExchangePayload) Reset() {
	*x = ContentExchangePayload{}
	mi := &file_anchor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentExchangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentExchangePayload) ProtoMessage() {}

func (x *ContentExchangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentExchangePayload.ProtoReflect.Descriptor instead.
func (*ContentExchangePayload) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{0}
}

func (x *ContentExchangePayload) GetMids() []string {
	if x != nil {
		return x.Mids
	}
	return nil
}

// PeerAddrInfoProto represents a single peer ID and multiaddresses.
type PeerAddrInfoProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs         []string               `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerAddrInfoProto) Reset() {
	*x = PeerAddrInfoProto{}
	mi := &file_anchor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAddrInfoProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAddrInfoProto) ProtoMessage() {}

func (x *PeerAddrInfoProto) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAddrInfoProto.ProtoReflect.Descriptor instead.
func (*PeerAddrInfoProto) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{1}
}

func (x *PeerAddrInfoProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerAddrInfoProto) GetAddrs() []string {
	if x != nil {
		return x.Addrs
	}
	return nil
}

// AnchorRegistryProto represents the persisted list of anchor nodes.
type AnchorRegistryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anchors       []*PeerAddrInfoProto   `protobuf:"bytes,1,rep,name=anchors,proto3" json:"anchors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnchorRegistryProto) Reset() {
	*x = AnchorRegistryProto{}
	mi := &file_anchor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnchorRegistryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnchorRegistryProto) ProtoMessage() {}

func (x *AnchorRegistryProto) ProtoReflect() protoreflect.Message {
	mi := &file_anchor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnchorRegistryProto.ProtoReflect.Descriptor instead.
func (*AnchorRegistryProto) Descriptor() ([]byte, []int) {
	return file_anchor_proto_rawDescGZIP(), []int{2}
}

func (x *AnchorRegistryProto) GetAnchors() []*PeerAddrInfoProto {
	if x != nil {
		return x.Anchors
	}
	return nil
}

var File_anchor_proto protoreflect.FileDescriptor

const file_anchor_proto_rawDesc = "" +
	"\n" +
	"\fanchor.proto\x12\n" +
	"membuss.v1\",\n" +
	"\x16ContentExchangePayload\x12\x12\n" +
	"\x04mids\x18\x01 \x03(\tR\x04mids\"9\n" +
	"\x11PeerAddrInfoProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\tR\x05addrs\"N\n" +
	"\x13AnchorRegistryProto\x127\n" +
	"\aanchors\x18\x01 \x03(\v2\x1d.membuss.v1.PeerAddrInfoProtoR\aanchorsB.Z,github.com/nnlgsakib/membuss/proto;membusspbb\x06proto3"

var (
	file_anchor_proto_rawDescOnce sync.Once
	file_anchor_proto_rawDescData []byte
)

func file_anchor_proto_rawDescGZIP() []byte {
	file_anchor_proto_rawDescOnce.Do(func() {
		file_anchor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anchor_proto_rawDesc), len(file_anchor_proto_rawDesc)))
	})
	return file_anchor_proto_rawDescData
}

var file_anchor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anchor_proto_goTypes = []any{
	(*ContentExchangePayload)(nil), // 0: membuss.v1.ContentExchangePayload
	(*PeerAddrInfoProto)(nil),      // 1: membuss.v1.PeerAddrInfoProto
	(*AnchorRegistryProto)(nil),    // 2: membuss.v1.AnchorRegistryProto
}
var file_anchor_proto_depIdxs = []int32{
	1, // 0: membuss.v1.AnchorRegistryProto.anchors:type_name -> membuss.v1.PeerAddrInfoProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anchor_proto_init() }
func file_anchor_proto_init() {
	if File_anchor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anchor_proto_rawDesc), len(file_anchor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anchor_proto_goTypes,
		DependencyIndexes: file_anchor_proto_depIdxs,
		MessageInfos:      file_anchor_proto_msgTypes,
	}.Build()
	File_anchor_proto = out.File
	file_anchor_proto_goTypes = nil
	file_anchor_proto_depIdxs = nil
}
