// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckExplorer():Promise<boolean>;

export function CheckForUpdate():Promise<main.UpdateCheckResult>;

export function CheckNodeStatus():Promise<Record<string, any>>;

export function ClearDaemonLogs():Promise<void>;

export function DownloadContent(arg1:string,arg2:string):Promise<string>;

export function ForceKillNode():Promise<void>;

export function GetAvailableVersions():Promise<Array<main.ReleaseOption>>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetShowBetas():Promise<boolean>;

export function GetDaemonLogs():Promise<string>;

export function GetNodeConfig():Promise<Record<string, any>>;

export function GetNodeConfigRaw():Promise<string>;

export function InstallBinaries(arg1:string):Promise<void>;

export function InstallVersion(arg1:string):Promise<void>;

export function IsNodeRunningSystemWide():Promise<boolean>;

export function OpenDataDir():Promise<void>;

export function ResetSetup():Promise<void>;

export function SaveConfig(arg1:main.DesktopConfig):Promise<void>;

export function SaveNodeConfig(arg1:Record<string, any>):Promise<void>;

export function SaveNodeConfigRaw(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetShowBetas(arg1:boolean):Promise<void>;

export function StartNode():Promise<void>;

export function StopNode():Promise<void>;

export function UpgradeBinaries():Promise<void>;

export function VerifyInstallation():Promise<Record<string, any>>;

export function WriteDefaultConfig():Promise<void>;
